### ISSUE TITLE
Command-line options

### ISSUE THREAD

**Issue by MistahWrite** [alexkay/spek#102]
I would like to output a maximized-sized .png file from spek using the command-line.  This way I can run Spek on 6 months of daily recordings using a batch file that I will write for Windows 7.  Thousands of recordings I need spectrograms for.  Thank you.  Will pay for this feature today.

Other Issues:
Also, I want to be able to play the opened mp3 file at the time location of the spectrogram so we can  just play the mp3 file from spek.

Also, as side feature requests:  audio explorer window that will process all mp3 file into spectrograms beneath a certain folder.

Another thing, I had some dataloss.  I need to run a .iso file thru Spek to find lost files on a disc image.  Ghost Hunting for MP3 files using Spek.  Thank you for our consideration.

**Comment by mcrozz** [comment]
Save spectrogram as an image from the command line? That would be a great feature!

**Comment by alexkay** [comment]
Command line options are covered by #9.

I don't plan to add playback support to Spek, there are already plenty of audio players.
