### ISSUE TITLE
ffmpeg 3.1.1 compatibility

### ISSUE THREAD

**Issue by dimm0k** [alexkay/spek#109]
unable to compile using 3.1.1 of ffmpeg

In file included from /usr/include/libavformat/avformat.h:317:0,
                 from spek-audio.cc:21:
/usr/include/libavcodec/avcodec.h:4414:6: note: declared here
 void av_free_packet(AVPacket _pkt);
      ^
spek-audio.cc:310:41: warning: ‘void av_free_packet(AVPacket_)’ is deprecated [-Wdeprecated-declarations]
             av_free_packet(&this->packet);
                                         ^
In file included from /usr/include/libavformat/avformat.h:317:0,
                 from spek-audio.cc:21:
/usr/include/libavcodec/avcodec.h:4414:6: note: declared here
 void av_free_packet(AVPacket _pkt);
      ^
Makefile:448: recipe for target 'libspek_a-spek-audio.o' failed
make[2]: *_\* [libspek_a-spek-audio.o] Error 1
make[2]: Leaving directory '/tmp/SBo/spek-0.8.2/src'
Makefile:368: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/spek-0.8.2'
Makefile:302: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by moesasji** [comment]
This error appears to result from the following change in ffmpeg code-base: https://ffmpeg.org/pipermail/ffmpeg-cvslog/2015-October/094920.html

So the fix is likely just replacing occurrences of av_free_packet with av_packet_unref

**Comment by alexkay** [comment]
Yep, it's already fixed, see #91.

**Comment by Tecolotl** [comment]
Hello people I managed to install Spek years ago, and now I can't compile it, you say to replace, but how to do that? what is the name of the file? or there is a command that must be followed after make? take care people :)

**Comment by Tecolotl** [comment]
> Hello people I managed to install Spek years ago, and now I can't compile it, you say to replace, but how to do that? what is the name of the file? or there is a command that must be followed after make? take care people :)

If to anyone it helps in the future, I managed to install spek from the git in Fedora 33 install dependencies g++ 7.2.1 wxWidgets 3.0.3 FFmpeg-3.3.6 and libtool. very important  ./autogen.sh CXXFLAGS=-I/usr/include/ffmpeg that fix some crashes.
 
dnf install libtool 

git clone git://github.com/alexkay/spek.git
    cd spek
    ./autogen.sh CXXFLAGS=-I/usr/include/ffmpeg   
    make  or  sudo make install
