### ISSUE TITLE
segmentation fault open certain mp3s

### ISSUE THREAD

**Issue by dimm0k** [alexkay/spek#111]
compiled spek-master with wxPython 3.0.2.0 and ffmpeg 3.1.2 and while spek works for some mp3 files, it seems to choke on VBR mp3s that I recently made with lame 3.99.5. any suggestions?

**Comment by alexkay** [comment]
Could you share a sample that causes segfaults?

**Comment by dimm0k** [comment]
hrmm, I've recently updated to the latest spek-master after mention of issue #109 being fixed and closed and it looks to be working flawlessly now. I suppose we can close this for now, thank you for following up!
