### ISSUE TITLE
Spek 0.8.2 cannot display certain freqs

### ISSUE THREAD

**Issue by NyanMetal** [alexkay/spek#112]
Spek 0.8.2 cannot display freqs 13500, 15000, 16500, 18000, others.
Sine tone generated in Audacity. file properties: 24bit/48kHz/mono.
[spekissue.zip](https://github.com/alexkay/spek/files/445610/spekissue.zip)

**Comment by alexkay** [comment]
0.8.5 shows it:

![15000 mp3](https://user-images.githubusercontent.com/49100/216880623-4c2e5b9d-985a-4096-a91c-e8fe368ec5f8.png)
