### ISSUE TITLE
Icons suggestion

### ISSUE THREAD

**Issue by DotTheI** [alexkay/spek#118]
![close](https://cloud.githubusercontent.com/assets/10737439/19031101/35c61eca-8963-11e6-84de-14ff6fd88187.png)
![help](https://cloud.githubusercontent.com/assets/10737439/19031102/35c671c2-8963-11e6-9d0c-ad667e341175.png)
![open](https://cloud.githubusercontent.com/assets/10737439/19031100/35c51b38-8963-11e6-8acf-ad71614a869d.png)
![save](https://cloud.githubusercontent.com/assets/10737439/19031103/35c85a32-8963-11e6-873e-27264fda6406.png)
![logo 1365274880](https://cloud.githubusercontent.com/assets/10737439/19031248/0df9258a-8964-11e6-92f5-1722e6ea9c91.png)

Found on the Internet, I am not sure about copyrights.

**Comment by alexkay** [comment]
Sorry, I can't use random icons, without making a proper attribution and without confirming it's compatible with Spek's license.
