### ISSUE TITLE
You should update Spek to use a newer version of libAVCodec

### ISSUE THREAD

**Issue by bumblebritches57** [alexkay/spek#122]
for one, DTS-HD is supported entirely now.

2, Spek won't launch on Sierra at all...

`Process:               Spek [18542]
Path:                  /Applications/Spek.app/Contents/MacOS/Spek
Identifier:            org.spek-project
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Spek [18542]
User ID:               501

Date/Time:             2016-11-29 18:43:48.881 -0500
OS Version:            Mac OS X 10.12.1 (16B2657)
Report Version:        12
Anonymous UUID:        703DB063-9DC0-FE4C-A9BF-C83DB78AF27B

Sleep/Wake UUID:       65E656C8-29EC-4326-9E05-5659E73FDD4B

Time Awake Since Boot: 70000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x248b8b5b  ebx: 0xbffffce0  ecx: 0x241499f5  edx: 0x00000001
  edi: 0xbffffd14  esi: 0x00000000  ebp: 0xbffffc98  esp: 0xbffffc50
   ss: 0x00000023  efl: 0x00010297  eip: 0x000011bb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     6
Error Code:      0x00000004
Trap Number:     14

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 49461
    thread_create: 0
    thread_set_state: 0
`

**Comment by alexkay** [comment]
The new version will use FFmpeg 3.2.2, I hope to release it in a few days.

**Comment by alexkay** [comment]
See #107 for the Sierra issue.
