### ISSUE TITLE
Don't UPX compress spek.exe for the next release

### ISSUE THREAD

**Issue by withmorten** [alexkay/spek#135]
Currently spek.exe is UPX compressed - which causes a slight but noticable delay when starting it up. This accumulates over time because it's a program you'll likely open hundreds if not thousands of times.

Decompressing it with upx -d results in spek starting up instantly.

The file sizes are 20,7MB uncompressed and 7,8MB compressed - this isn't really a filesize where compression would actually help that much. I'm sure everybody has those extra 12MB for a program that they'll want to start up very, very often.

**Comment by alexkay** [comment]
This is fixed.
