### ISSUE TITLE
Spek crashing on MacOS due to bad UPX packing

### ISSUE THREAD

**Issue by sebmellen** [alexkay/spek#136]
Still a problem on Sierra. A fix would be appreciated.

However....

I have a recompiled binary that is fully working. I will link if any of you'd like me to!

**Comment by withmorten** [comment]
Check the 0.8.4 version on here, works fine: https://github.com/alexkay/spek/releases/tag/v0.8.3

I've already opened up another issue suggesting not UPX packing spek at all for the next release: https://github.com/alexkay/spek/issues/135

It causes more problems than it solves (many to none, basically), in my opinion.

**Comment by sebmellen** [comment]
Interesting. Good to hear. Why does the 0.8.4 release show up as 0.8.2?

**Comment by withmorten** [comment]
No version change in the configure.ac since it's not really a proper release yet, most likely. Also so it gives you an update notification once the update to 0.8.4 or so actually does happen.
