### ISSUE TITLE
Sierra

### ISSUE THREAD

**Issue by yokeless** [alexkay/spek#138]
Hello,

First, thanks for this app, very useful and well coded.
It was working fine with previous version of OSX but with Sierra it doesn't launch.

Does anyone have an idea on how it could work fine with Sierra ? or maybe an update ?

regards,

yokeless

**Comment by tr1s** [comment]
0.8.4 Alpha works --> https://github.com/alexkay/spek/releases/tag/v0.8.3

Someone should close all these Sierra related ones!

**Comment by motiko** [comment]
0.8.4 alpha crashes in my Sierra

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by tr1s** [comment]
> I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

Working great for me, thank you!

The previous version I had was crashing every second time.

**Comment by alexkay** [comment]
Fantastic, thank you for confirming!
