### ISSUE TITLE
Allow grayscale colors

### ISSUE THREAD

**Issue by PiotrGrochowski** [alexkay/spek#140]
I would like to see how spek spectrograms sound. Unfortunately, spek spectrograms do not have consistently increasing or decreasing brightness, so I couldn't properly hear it by any means. Grayscale colors would fix it by having consistent ascending or descending brightness.

**Comment by alexkay** [comment]
It's already implemented in master: https://github.com/alexkay/spek/commit/3cc57547c7a5e07be14480e041d08a77ab79383c

**Comment by PiotrGrochowski** [comment]
How to use it with Windows?
