### ISSUE TITLE
No padding on Spek, app cuts off kHz and db.

### ISSUE THREAD

**Issue by tr1s** [alexkay/spek#141]
Windows 10: App cuts off the first number of all the kHz, and half of the "B" in "dB". There doesn't seem to be any padding in the app. 

macOS Sierra: App doesn't even open.

![speknopadding](https://user-images.githubusercontent.com/19172250/27613864-f780fe6a-5b6b-11e7-9f76-5a4fc8226c56.png)

**Comment by fuzun** [comment]
Did you change Windows scaling?

**Comment by tr1s** [comment]
@fuzun I'm on a Retina MacBook Pro running Windows natively on a partition of my hard-drive, so I guess Spek is just not meant for Retina right now?

**Comment by tr1s** [comment]
@fuzun OK so my scaling is automatically set to 200% because of my Retina screen.. so bringing it down to 100% makes Spek look perfect... but then I need eagle vision ha.

![display100percent](https://user-images.githubusercontent.com/19172250/27614174-f8005186-5b6d-11e7-99e2-cc68f6c2368c.png)

**Comment by fuzun** [comment]
Set scaling to whatever you want then right click Spek.exe go options and check "Disable display scaling on high DPI settings".

Try this.

**Comment by tr1s** [comment]
@fuzun Nope. Tried that, tried compatibility mode for all options as well, nothing worked.

**Comment by fuzun** [comment]
Possible relation: #113

**Comment by withmorten** [comment]
I just experimented on my Windows 10 machine and the option "Override high DPI scaling behavior" works for me when set to "System", with 200% scaling. It uses Windows 10 version 1073. The saved images are also the proper resolution so that they can be viewed on smaller screens (i.e. not 1000x1000 something).

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
