### ISSUE TITLE
Ability to display frequencies above 22KHz

### ISSUE THREAD

**Issue by syuilo** [alexkay/spek#145]
Thanks for this great app.

**Comment by fuzun** [comment]
It already shows.

**Comment by jvineaudio** [comment]
The 22KHz cap that you are seeing is probably because you were analyzing a file with a 44.1KHz sample rate which doesn't allow frequencies higher than 22KHz (Limitation of the encoding and not Spek). Files with higher sample rates will be able to display higher frequencies.

**Comment by alexkay** [comment]
The max frequency is always half for the sample rate, see https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem
