### ISSUE TITLE
OSX Sierra 10.12.6 - Spek Not working

### ISSUE THREAD

**Issue by larosamusic** [alexkay/spek#147]
This might be a duplicate but Spek is not working on this os. I tried the alpha build and it still crashes. Any update on a version to work with this system?

**Comment by larosamusic** [comment]
Now it worked. Let you know if anything changes... 

Thx

**Comment by cchyung** [comment]
What did you do to make it work?

**Comment by Roger74** [comment]
larosamusic, can you please describe what you did, to make it work.

Thnx,
Roger

**Comment by JanDeMircadale** [comment]
0.8.3 causes segmentation fault on launch. 0.8.4 alpha works.

**Comment by Marak** [comment]
Confirmed that `0.8.4` no longer crashes on OSX Sierra `10.12.6`.

Thank you for making Spek @alexkay. 

Spek has really helped me and is a very useful tool.

**Comment by Bachomp** [comment]
For me, 0.8.4 alpha is crashing on MacOS 10.12.6

**Comment by cuhieptinhte** [comment]
I FOUND A WORKAROUND, AND POST THE FILE ON THIS - I WORKS!!!
https://github.com/alexkay/spek/issues/155

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
