### ISSUE TITLE
Include error when compiling with ffmpeg-3.3.x

### ISSUE THREAD

**Issue by 404NetworkError** [alexkay/spek#149]
## Edit (1-26-2018):
See @goapunk's [comment](https://github.com/alexkay/spek/issues/149#issuecomment-360799464) for a better solution. Still doesn't fix the original problem.

### Updated Build Environment:
- Fedora 27
- g++ 7.2.1 (from Fedora - Updates)
- wxWidgets 3.0.3 (from Fedora - Updates)
- FFmpeg-3.3.6 (from RPM Fusion - Free - Updates)
---
## Original Issue:
I am running into an error when compiling the git-ac482d7 version. The error is:
```
In file included from spek-spectrogram.cc:7:0:
spek-fft.h:7:10: fatal error: libavutil/mem.h: No such file or directory
```

Using `./autogen.sh --enable-dependency-tracking --disable-silent-rules` to give a more detailed description of the exact compilation instructions, I get this as the command being run:
```
g++ -DHAVE_CONFIG_H -I. -I..  -include config.h -pthread -I/usr/lib64/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__   -g -O2 -std=gnu++11 -Wall -Wextra -MT spek-spek-spectrogram.o -MD -MP -MF .deps/spek-spek-spectrogram.Tpo -c -o spek-spek-spectrogram.o `test -f 'spek-spectrogram.cc' || echo './'`spek-spectrogram.cc
```

The problem is that the FFmpeg includes aren't getting passed to g++ during this step.  I was able to solve this by adding  `-I/usr/include/ffmpeg` to the configure.ac CXXFLAGS so that it became:
```
CXXFLAGS="$CXXFLAGS -std=gnu++11 -Wall -Wextra -I/usr/include/ffmpeg"
```
While this works for my setup, I don't know if this would cause a problem for people using libav or other Linux/Unix environments.
- - -
### Build Environment:
- Fedora 26
- g++ 7.2.1 (from Fedora - Updates)
- wxWidgets 3.0.3 (from Fedora - Updates)
- FFmpeg-3.3.4 (from RPM Fusion - Free - Updates)

**Comment by arigit** [comment]
Same issue / similar environment - your fix worked, thanks!

**Comment by torbjorn** [comment]
Same issue, fix worked, very grateful!

**Comment by rickrich** [comment]
Fedora 26.  Same issue.  Your fix worked!

**Comment by goapunk** [comment]
you can also pass the CXXFLAGS directly to autogen.sh:
`./autogen.sh CXXFLAGS=-I/usr/include/ffmpeg`

**Comment by 404NetworkError** [comment]
@goapunk Thanks for the suggestion. I can confirm that this works too and is a better solution than mine.

**Comment by alexkay** [comment]
Closing as obsolete, Spek now compiles with ffmpeg 5.1.

**Comment by MobCode100** [comment]
> you can also pass the CXXFLAGS directly to autogen.sh: `./autogen.sh CXXFLAGS=-I/usr/include/ffmpeg`

I'd still find this solution is needed to compile spek in Fedora 38. Thanks!.
