### ISSUE TITLE
Segmentation fault: 11 on macOS 10.13.3

### ISSUE THREAD

**Issue by lightning541** [alexkay/spek#160]
**Error: Segmentation Fault: 11
OS: macOS 10.13.3
Spek Version: 0.8.2**

Time Awake Since Boot: 260000 seconds

System Integrity Protection: disabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000cec933b
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x0008950c  ebx: 0xbffffce8  ecx: 0x0cec933b  edx: 0x00000001
  edi: 0xbffffd18  esi: 0x00001000  ebp: 0xbffffca8  esp: 0xbffffc60
   ss: 0x00000023  efl: 0x00010297  eip: 0x000013e3   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x0cec933b
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 110326
    thread_create: 0
    thread_set_state: 0

**Comment by kishabasu** [comment]
I will be trying to install this for my class tomorrow. I am not sure of the version of OSX they have on the school computers. Is this issue only for the latest version (10.13.3) of OSX?
Thanks!

**Comment by lightning541** [comment]
That, I am not aware of as I don't have other device with an older macOS...

**Comment by leematos** [comment]
I just hit this too on 10.12.5. :(

**Comment by withmorten** [comment]
Can you try this version?

https://github.com/withmorten/spek-alternative/releases

**Comment by leematos** [comment]
@withmorten yep! Worked. Was able to open and view files! Thanks!

**Comment by lightning541** [comment]
Oh, my goodness. It worked! Thank you so much, @withmorten!

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
