### ISSUE TITLE
ffmpeg2.8 no longer in AUR; spek cannot be built on Arch

### ISSUE THREAD

**Issue by fictionic** [alexkay/spek#161]
see title

**Comment by fictionic** [comment]
ok well I guess it's back. nvm! Though really the dependency should be switched to straight ffmpeg if posssible. Not that I know any details.

**Comment by elisaado** [comment]
It's gone again :/

**Comment by fictionic** [comment]
Alright @alexkay, can you explain why the dependency is on 2.8 instead of regular ffmpeg?

**Comment by alexkay** [comment]
The master doesn't depend on 2.8, I will cut a new release in the next few weeks, or just build from source.

**Comment by TacoTheDank** [comment]
@alexkay ~~dont take 2 1/2 years this time lmao~~

**Comment by DirectorX** [comment]
@alexkay please tag new release...

**Comment by alexkay** [comment]
A new release is out, it works with ffmpeg 5.1
