### ISSUE TITLE
Spek won't run on High Sierra 10.13.3

### ISSUE THREAD

**Issue by 0m3nC0w** [alexkay/spek#162]
Spek immediately crashes when opened. I am running High Sierra 10.13.3 on a brand new MacBook Pro Retina Touchbar. Here is a copy/paste of the report (I've attached it as a text file as well). I hope you can get it to run as it looks like a really cool app.
[Spek Crash Report.txt](https://github.com/alexkay/spek/files/1799649/Spek.Crash.Report.txt)

![screenshot 2018-03-10 10 12 52](https://user-images.githubusercontent.com/37249324/37245377-f881262e-244b-11e8-98dd-a2815852bb2d.jpg)

**Comment by geberl** [comment]
Same thing for me on 10.13.3.
As suggested in https://github.com/alexkay/spek/issues/160 by @withmorten spek-alternative 0.8.2.3 works.

**Comment by andreumateulamas** [comment]
I am on High sierra .10.3. 5 and I have the same proplem.. SPEK DOES NOT WORK.
 
I AM GOING TO TO TRY THAT ALTERNATIVE.

**Comment by eahdawn** [comment]
Same issue here on  10.13.4. Trying spek-alternative 0.8.2.3.

**Comment by Marak** [comment]
@andreumateulamas -

Thought [this link](https://www.wikihow.com/Turn-Off-Caps-Lock) might help you. 

 Cheers!

**Comment by andreumateulamas** [comment]
Marak..

Thanks. This link might help you also.
http://www.cracked.com/blog/5-simple-steps-to-not-being-total-asshole/

**Comment by andreumateulamas** [comment]
I was not yelling... Capital letters to me was is bold or underline... Just to remark the problem. 
Do you go through life yelling everytime you read some capital letters?
You will get aphony... In every corner I read names of shops, restaurants and other  in capital letters.

**Comment by dzz007** [comment]
Looks like the upx broke under newer version of MacOS. 
You guys can try this alternative: https://github.com/withmorten/spek-alternative/releases
Or if you wanna fix it yourself, use brew to download upx by doing `brew install upx`
Then run `upx -d <executable_path>` to decompress the executable and it would work
<executable_path> example: "/Applications/Spek.app/Contents/MacOS/Spek"

**Comment by withmorten** [comment]
I'd suggest using my version instead because it uses more recent ffmpeg libraries (and thus fixes many bugs related to the old ffmpeg libraries in the current speak release). :)

**Comment by andreumateulamas** [comment]
I think it works... THANKS.

**Comment by mattpopovich** [comment]
See #160. I recommend to close this duplicate issue.
