### ISSUE TITLE
text overflow in high resolution screen

### ISSUE THREAD

**Issue by aoxiangwu** [alexkay/spek#164]
The text in y axis overflow!!
OS: win10_1709
Device: Surface Pro 4
Resolution: 2736x1824
<img src="https://i.loli.net/2018/05/03/5aeab0c31c71e.png" alt="issue.png" title="issue.png" />
I can't see the value of kHz.

**Comment by withmorten** [comment]
Set "Override High DPI scaling behavior" to performed by "System" in the compability options.

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
