### ISSUE TITLE
Can't open an MP3 file

### ISSUE THREAD

**Issue by Derp0** [alexkay/spek#165]
Spek detects this MP3 file as "Unknown duration: PCM signed 16-bit little-endian, 13873 Hz, 16 bits" (Sampling rate randomly changes):

> Audio
> Format                      : MPEG Audio
> Format version              : Version 1
> Format profile              : Layer 3
> Duration                    : 5 min 12 s
> Bit rate mode               : Constant
> Bit rate                    : 192 kb/s
> Channel(s)                  : 2 channels
> Sampling rate               : 44.1 kHz
> Frame rate                  : 38.281 FPS (1152 SPF)
> Compression mode            : Lossy
> Stream size                 : 7.15 MiB (100%)
> Writing library             : LAME3.93

If the file is needed, tell me where to upload.

**Comment by withmorten** [comment]
Can you upload this to zippyshare.com / dbr.ee?

**Comment by Hacktivator** [comment]
https://dbr.ee/MdAR

Not the same file. Yet getting an error. I got quite a few with errors. The only error though is Unknown duration.

**Comment by withmorten** [comment]
Try this: https://github.com/withmorten/spek-alternative/releases

Probably related to outdated ffmpeg libraries. Quite a lot of problems with mp3 files with covers. Works fine on my build though.

**Comment by xekon** [comment]
Is there a way to enable debugging or something so that I can get some clues as to why the file will not open? every mp3 file I try to open with spek does not work:

![image](https://user-images.githubusercontent.com/106644/78086078-ba297800-7371-11ea-8111-30527914a240.png)

**Comment by alexkay** [comment]
Please share a sample if you are still seeing the error with 0.8.5: https://github.com/alexkay/spek/releases/tag/v0.8.5
