### ISSUE TITLE
chocolatey package for spek is deprecated

### ISSUE THREAD

**Issue by czhang03** [alexkay/spek#166]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for spek.
  I am deprecating the chocolatey package for spek because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/416
  The chocolatey package page for spek : https://chocolatey.org/packages/spek

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by alexkay** [comment]
@chantisnake, did you find a new maintainer? If not I could advertise this on the website.

**Comment by czhang03** [comment]
according to the issue https://github.com/chocolatey-community/chocolatey-package-requests/issues/416, it seems like they found a new maintainer.
