### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [alexkay/spek#173]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Spek on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by absolutelynothinghere** [comment]
An AppImage might be more suitable: https://github.com/withmorten/spek-alternative/issues/11

**Comment by alexkay** [comment]
This is worked on, see #256.
