### ISSUE TITLE
malicious

### ISSUE THREAD

**Issue by solartony** [alexkay/spek#175]
malware patrol detects malicious malware in the tar file ... why ?

**Comment by withmorten** [comment]
Which tar file?

**Comment by solartony** [comment]
> Which tar file?

https://github.com/alexkay/spek/releases/download/v0.8.2/spek-0.8.2.tar.xz

**Comment by withmorten** [comment]
No idea in that case. It's just an archive with harmless source files.

**Comment by solartony** [comment]
could it be the tar algorithm ?

https://github.com/alexkay/spek/releases/download/v0.8.2/spek-0.8.2.zip
spek.exe Trapmine suspicious.low.ml.score

**Comment by mvasilkov** [comment]
False positive, I assume.

**Comment by alexkay** [comment]
Must be a false positive, there's no way malware could get into the builds I published (let alone source code tarballs). You are welcome (and encouraged!) to build Spek from source code yourself instead of trusting strangers on the Internet :)

**Comment by withmorten** [comment]
The windows exe is packed with UPX, so that's why it's suspicious. Still nothing malicious in it though.

**Comment by alexkay** [comment]
Could be. FWIW, I'm going to drop UPX in the future builds.

**Comment by solartony** [comment]
> Could be. FWIW, I'm going to drop UPX in the future builds.

what compiler have you used/recommend for a build win64 ?
thx all for all your good work .... !

**Comment by withmorten** [comment]
I don't think there currently is a way to build for win64. The build.sh only works for win32 mxe gcc.

**Comment by alexkay** [comment]
Correct, I haven't tried to build for win64. You could give `mxe64` or `mingw-w64` a go.
