### ISSUE TITLE
Mac and PC showing different results for the same song?

### ISSUE THREAD

**Issue by george990** [alexkay/spek#177]
Hi

I have found an issue with the results spek is giving on my mac. I ran the same song though my mac and on a pc. The pc version is showing a completely different graph to my mac. The song looks a lot better quality on the PC scan compared to my mac.

Is this a known issue between mac and pc for this software? also is there any way to fix it?

Thanks

**Comment by withmorten** [comment]
Check this comment: https://github.com/alexkay/spek/issues/168#issuecomment-499925420

**Comment by alexkay** [comment]
Confirming. If that doesn't explain what you are seeing, please include screenshots for both.
