### ISSUE TITLE
How do I build a portable version on windows 10?

### ISSUE THREAD

**Issue by stephen147** [alexkay/spek#179]
I read this but it's only to build an [msi](https://github.com/alexkay/spek/blob/master/dist/win/README.md). I cannot find any guides to do this

**Comment by withmorten** [comment]
The build process leaves a Spek.zip, out of which the msi installer is created. The build process is detailed in the same file you linked.

**Comment by stephen147** [comment]
Thanks. I'll give it a try. I was trying to see if I could modify it and add a larger icon to `spek.exe`.

**Comment by withmorten** [comment]
You don't need to recompile the program for that. A tool like Resource Hacker will work just fine for replacing .exe resources, like icons.

**Comment by stephen147** [comment]
### I've tried that but the save button is greyed out:
![new gif](https://user-images.githubusercontent.com/14054664/61182964-c0849200-a632-11e9-9008-c1bf33e4473f.gif)

### I've also tried using `rcedit`:
But this corrupts the file somehow.
```
set "exeRoot=Z:\Music\Apps Music (Portable)\Spek"
"rcedit\rcedit-x64.exe" "%exeRoot%\spek.exe" --set-icon "%exeRoot%\4.ico"
```

**Comment by withmorten** [comment]
Perhaps you need to start Resource Hacker with admin rights? Or try save as?

**Comment by stephen147** [comment]
Sorry, that I have tried. And I tried to close RH and only then it gives the option to save but this corrupts the `.exe`.
