### ISSUE TITLE
64-bit port?

### ISSUE THREAD

**Issue by KEXINO** [alexkay/spek#181]
Any plans for a 64-bit port, to support OS X Catalina?

**Comment by dtrombly** [comment]
This would be more than appreciated.

**Comment by gregforcey** [comment]
The forked version works in Catalina for me: https://github.com/withmorten/spek-alternative/releases

**Comment by mattpopovich** [comment]
This is a duplicate of #180 and #168. Recommending to close it.

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
