### ISSUE TITLE
Latest build is not up to date

### ISSUE THREAD

**Issue by reallyuniquename** [alexkay/spek#184]
Is there an official release for Windows and other OSes built from latest sources? There were [tons of fixes and features](https://github.com/alexkay/spek/compare/v0.8.3...master) added since v0.8.3.

I see users keep requesting things that were already implemented because latest build is not up to date.

**Comment by birdie-github** [comment]
The original creator of this application, @alexkay , has effectively disappeared (zero public activity in github for the last two years), so it's unfeasible to expect new builds.

Hopefully someone with fork the project and let it live on.

**Comment by withmorten** [comment]
I created a fork a couple of years ago here, but have not gotten around to push my latest update yet either:

https://github.com/withmorten/spek-alternative/

Should work MUCH better than the original version on especially macOS and Windows anyway.

**Comment by wdlkmpx** [comment]
Fresh Windows builds are required.

Hmm everyone should probably be using builds from https://github.com/withmorten/spek-alternative/

**Comment by alexkay** [comment]
I added updated beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
