### ISSUE TITLE
Doesn't work in macOS Catalina

### ISSUE THREAD

**Issue by jpsalap** [alexkay/spek#187]
Because of the macOS transition from 32bits to 64bits this app is not optimized. Hope this can be solved soon.

**Comment by neonUneon** [comment]
The issue below about 64-bit has a working link, have to bypass security check in System Preferences->Security & Privacy.

https://github.com/withmorten/spek-alternative/releases

**Comment by fredOnGitHub** [comment]
Hello,
i confirm. The pig logo is crossed out

**Comment by mattpopovich** [comment]
This is a duplicate of #181. Recommending to close it.

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
