### ISSUE TITLE
A guide for building Windows executable 

### ISSUE THREAD

**Issue by kennybush** [alexkay/spek#189]
I was trying to build Windows executable but fail with errors. Fortunately after some research I was success. Here are some experience.

1. build MXE tool fail with cmd "make pthreads ffmpeg wxwidgets -j8 JOBS=8"

- Use the Ubuntu environment, update all the components and try again ( I can build success in WSL Ubuntu 18.04 lts, and fail in CentOS 7.10)
- Not need to patch "mxe.diff", it may not work with lastest MXE ;)
- A stable network. During building you need to confirm google.com can be accessing. 

2. build Spek fail with error "possibly undefined macro: AM_OPTIONS_WXCONFIG"

- Edit "autogen.sh" in project root dir, add " -I ../mxe/usr/i686-w64-mingw32.static/share/aclocal/" after "autoreconf -fiv" in line 9

![_20200501230505](https://user-images.githubusercontent.com/42364884/80815448-3d075200-8c00-11ea-9c81-c913bfe28801.png)

**Comment by alexkay** [comment]
These should be fixed on `master`.
