### ISSUE TITLE
Not available in Ubuntu repository for 20.04 LTS

### ISSUE THREAD

**Issue by erwanosouf** [alexkay/spek#191]
Could you make this great software available for Ubuntu 20.04 LTS ?

Thanks !

**Comment by marcosscriven** [comment]
@alexkay  I just tried compiling from source in Ubuntu Focal 20.04.

First issue was getting the right dependencies.

1. gtk 2.8 not available, so I installed `libwxgtk3.0-gtk3-dev`
2. I also had to install `sudo apt install intltool`, as autoconf needed it.

All seemed to make fine, but then on startup I get a GTK error, so I suppose some incompatibility with GTK 3.0 needs to be fixed:

```
ASSERT INFO:
../src/common/iconbndl.cpp(293): assert "icon.IsOk()" failed in AddIcon(): invalid icon

BACKTRACE:
[1] wxIconBundle::AddIcon(wxIcon const&)
[2] wxIconBundle::wxIconBundle(wxIcon const&)
[3] wxArtProvider::GetIconBundle(wxString const&, wxString const&)
[4] wxArtProvider::DoGetIconBundle(wxString const&, wxString const&)
[5] wxArtProvider::GetIconBundle(wxString const&, wxString const&)
[6] wxEntry(int&, wchar_t**)
[7] __libc_start_main
```

**Comment by popey** [comment]
I built a snap of spek, which works on Ubuntu 20.04. 
https://snapcraft.io/spek

**Comment by blinkenlight** [comment]
@marcosscriven To get rid of that error, find the file spek-window.cc and comment out the following line (line61):
    SetIcons(wxArtProvider::GetIconBundle(ART_SPEK, wxART_FRAME_ICON));
Boom, error gone.

**Comment by CharAznableLoNZ** [comment]
I would also like to second spek being added into the 20.04 repository.  I tried the snap version however it was unable to ready any files due to it being a snap.

**Comment by CharAznableLoNZ** [comment]
At this point, maybe it would best for the ask to be on the upcoming 22.04 LTS repository seeing as we've gotten nothing in the last two years.

**Comment by absolutelynothinghere** [comment]
Consider using an AppImage? See https://github.com/withmorten/spek-alternative/issues/11

**Comment by InvisibleRain** [comment]
Runs like a charm through WINE

**Comment by alexkay** [comment]
Spek is added back to Debian and should be picked up by Ubuntu and other derivatives soon: https://tracker.debian.org/pkg/spek
