### ISSUE TITLE
Extra blank time at the end of MP3 file

### ISSUE THREAD

**Issue by twamer64** [alexkay/spek#195]
I had some m4a files and I converted them to mp3 with iTunes. But when I opened some of the converted mp3 files with spek 0.82 it shows extra blank time at the end. In one example, both the m4a and mp3 files are 02:44 minutes long but when I open the mp3 file with spek it shows that it is 03:01 minutes long and the extra seconds at the end are blank with no sound. In file properties in windows as well as music players it shows 02:44. Is there a reason it shows up differently in spek ?
![01 Daftendirekt m4a](https://user-images.githubusercontent.com/66408014/83726108-b9e87a00-a64b-11ea-9eb1-c50f32202681.png)
![01 Daftendirekt mp3](https://user-images.githubusercontent.com/66408014/83726160-cb318680-a64b-11ea-9ce7-0585d257b956.png)

**Comment by reydus** [comment]
Is there any chance you can provide me with said file?

**Comment by alexkay** [comment]
This is likely fixed in the new version that includes much newer ffmpeg libraries. Try it out and if it still doesn't work please include a sample demonstrating the error: https://github.com/alexkay/spek/releases/tag/v0.8.5
