### ISSUE TITLE
Fonts on Y axis not visible 

### ISSUE THREAD

**Issue by wayneLaw1** [alexkay/spek#196]
The Y axis of the graph first numbers are not visible
![y axis](https://user-images.githubusercontent.com/65870812/84944591-ea192980-b0dd-11ea-9701-5d6106472d70.jpg)

**Comment by J4K8B** [comment]
In my case the numbers did not show up at all on the Y axis. If the problem occurs in Windows 10, the temporary solution I applied was setting the High DPI Scaling Override so the System does the scaling. This can be done by accessing the spek.exe Properties -> Compatibility [tab] -> Change High DPI Settings. I attach PrtScreens. Hope it helps anyone who has the same problem and needs to use Spek right away in Windows. 
![Capture](https://user-images.githubusercontent.com/37769714/85343735-e9253500-b4ed-11ea-836b-daab153f84e1.JPG)
![Capture2](https://user-images.githubusercontent.com/37769714/85343742-ecb8bc00-b4ed-11ea-8fc7-89afdaa7d40c.JPG)

**Comment by wayneLaw1** [comment]
Thanks that worked.

**Comment by RattusSolarus** [comment]
I have the same problem in Debian Buster Linux on 3840x2160 screen. It's fine on 1920x1080 screen with same OS. HiDPI support for Spek would be excellent.

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
