### ISSUE TITLE
Mac OS 10.15.5 Support

### ISSUE THREAD

**Issue by ChathuraP** [alexkay/spek#197]
Hi Developers,
Please help to update this awesome software to latest Mac OS.

Thanks.

**Comment by mattpopovich** [comment]
See #187. I recommend to close this duplicate issue.

**Comment by KeithSloan** [comment]
Would also like to see the App updated for Mac OS 10.15

**Comment by ChathuraP** [comment]
Let us know once you update your app, will close the issue.

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
