### ISSUE TITLE
Lisibility of spectrum

### ISSUE THREAD

**Issue by dekol6** [alexkay/spek#200]
Hi,

I ve discovered spec few days ago, (sorry poor english)
And I understood that when a MP3 320 kbps , it appears in spec with 20.5 Khz graph.

But I recently analyse a 160 kbps MP3, and the graph in spec display me 20Khz graph.

[http://wassing.free.fr/forums/20210113101730spec.png](url)
`[IMG]http://wassing.free.fr/forums/20210113101730spec.png[/IMG]`
Is it a bug ? 

Regards,

**Comment by alexkay** [comment]
I'm not familiar with mp3 encoding details, but this could be expected for a high quality mp3 vbr encoder even at 160 kbps.
