### ISSUE TITLE
Spec Not Working in Mac OS Big Sur 

### ISSUE THREAD

**Issue by jayanta2009** [alexkay/spek#205]
When trying to open from application getting the following message
<img width="483" alt="Screen Shot 2021-05-20 at 6 19 53 PM" src="https://user-images.githubusercontent.com/17881955/119056121-2319e800-b998-11eb-893d-bd05ad1c1996.png">

The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.

**Comment by djaytek** [comment]
+1
Spek seems only compatible with intel cpu's according to spek website. So we will need to wait a bit until they port it to M1 chips.

**Comment by deweixu** [comment]
> +1
> Spek seems only compatible with intel cpu's according to spek website. So we will need to wait a bit until they port it to M1 chips.

It's not a CPU problem, I'm an Intel and I'm having the same problem

**Comment by samstator** [comment]
> > +1
> > Spek seems only compatible with intel cpu's according to spek website. So we will need to wait a bit until they port it to M1 chips.
> 
> It's not a CPU problem, I'm an Intel and I'm having the same problem

Spek won't run (or won't run properly at least) on anything above macOS Sierra iirc. The program itself hasn't been updated in 5 years. This is one of those rare moments where I miss Windows' legacy support-system.

**Comment by cuhieptinhte** [comment]
try this: https://github.com/withmorten/spek-alternative/releases/tag/0.8.2.3 version it works my Mac BigSure latest (intel/ however someone tested ok with M1 too)

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
