### ISSUE TITLE
Spek error

### ISSUE THREAD

**Issue by djmikkah** [alexkay/spek#206]
Spek will not open and it makes an error log. 
I have not had problems with it before and have not made any updates.

What to do?

Process:               Spek [2069]
Path:                  /Applications/Spek.app/Contents/MacOS/Spek
Identifier:            org.spek-project
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Spek [2069]
User ID:               501

Date/Time:             2021-07-03 12:41:21.727 +0200
OS Version:            Mac OS X 10.12.6 (16G2136)
Report Version:        12
Anonymous UUID:        1B390E0E-34F4-C899-79A6-C9B027E016C1

Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x248b8b5b  ebx: 0xbffffd28  ecx: 0x241499f5  edx: 0x00000001
  edi: 0xbffffd58  esi: 0x00000000  ebp: 0xbffffce8  esp: 0xbffffca0
   ss: 0x00000023  efl: 0x00010297  eip: 0x000011bb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1323
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro9,2, BootROM 228.0.0.0.0, 2 processors, Intel Core i5, 2,5 GHz, 16 GB, SMC 2.2f44
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x4B485831363030433953334C2F3847202020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x4B485831363030433953334C2F3847202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (7.21.171.134.1a2)
Bluetooth: Version 5.0.5f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
