### ISSUE TITLE
Can't show full screen

### ISSUE THREAD

**Issue by eagle0719** [alexkay/spek#207]
I cannot see full screen below on Win 10. Left bar does not show number, title in top bar cannot be displayed fully.
![image](https://user-images.githubusercontent.com/5717339/126623245-2441305c-4d88-42ab-b34f-3dc09b274164.png)

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
