### ISSUE TITLE
 Mac Big Sur should use version 0.8.2.3 alternative (update Aug. 2021)

### ISSUE THREAD

**Issue by cuhieptinhte** [alexkay/spek#208]
Today, Aug. 4th 2021, I tested this https://github.com/withmorten/spek-alternative/releases/tag/0.8.2.3 

it works with dmg installation file!
my Mac: Big Sur 11.15  - chip Intel

someone told that it works on M1 too : https://github.com/alexkay/spek/issues/201 

thanks you for the great job

**Comment by T0ddz** [comment]
Thanks, it works fine on Monterey 12.1 with Intel Core at Jan. 9th 2022, https://github.com/withmorten/spek-alternative/releases/tag/0.8.2.3

**Comment by s0lid** [comment]
Working on my M1 Big Sur thank you for sharing

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by edisun3003** [comment]
this one works on Monterey 12.7.6 T - https://github.com/withmorten/spek-alternative/releases/tag/0.8.2.3
this doesn't work -Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
