### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wppp2114** [alexkay/spek#209]
I cannot fully visualize the spectrogram values. I have an laptop with two screens, the model is ASUS ZENBOOK FLIP Q547F. this laptop has the main screen and un adicional screen in the mousepad, called the screenpad, i'm not sure if that's responsible for the problem. The program´s version 0.8.2
![Captura de pantalla 2021-08-0 140313](https://user-images.githubusercontent.com/71799278/128745530-5d450193-6f28-48ed-9d1d-7d5d5ee7822b.png)
![Captura de pantalla 2021-08-09 140313](https://user-images.githubusercontent.com/71799278/128745535-5d59627f-8590-4fd0-9870-75e1c64aca52.png)

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
