### ISSUE TITLE
Couldn't install on ubuntu 21.10

### ISSUE THREAD

**Issue by Nirzak** [alexkay/spek#213]
The software's dependencies are not up to date which is causing umet dependency errors on the latest versions of ubuntu. It throws the below error.

configure: error: Package requirements (libavcodec >= 53.25 libavformat >= 53.17 libavutil >= 51.17) were not met:

No package 'libavcodec' found
No package 'libavformat' found
No package 'libavutil' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FFMPEG_CFLAGS
and FFMPEG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

**Comment by O1Si** [comment]
`apt install libavcodec-dev libavformat-dev libavutil-dev`

**Comment by alexkay** [comment]
0.8.5 now works with ffmpeg 5.1
