### ISSUE TITLE
Windows 10 Pro - Graph too large for window border

### ISSUE THREAD

**Issue by AlphaHasher** [alexkay/spek#226]
![59ucONoV0j](https://user-images.githubusercontent.com/33443001/164176414-41941ef4-db1b-44b9-b872-40f3f6d4b455.gif)

**Comment by vitoremanueldesign** [comment]
I second this, do we have a solution?

**Comment by Codingboy65** [comment]
Nope

**Comment by rbrcooper** [comment]
I'm having the same issue.

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
