### ISSUE TITLE
Spek isn't launching on Mac

### ISSUE THREAD

**Issue by bexleymellish** [alexkay/spek#227]
Hello everyone, I am a complete novice in coding and computer in general, 
but I downloaded Spek in order to analyze the tracks that I use for DJing. 

Unfortunately, Spek didn't launch and it is giving me a relaunch option which at every attempt it fails to launch. 

I am on MacOS Mojave ver. 10.14.6

I would appreciate any help. thank you

**Comment by djmp1985** [comment]
I am having the same issue,  and I am running the same OS.

**Comment by bexleymellish** [comment]
I’m wondering what can we do. Seems like spek isn’t being developed for mac.

**Comment by wc7086** [comment]
I don't have os x system, can you start from command line to see the error message?

**Comment by gkostov** [comment]
@bexleymellish , as mentioned here https://github.com/alexkay/spek/issues/208 there is a fork that still works (Monterey on Intel) https://github.com/withmorten/spek-alternative/releases/download/0.8.2.3/spek-alternative-0.8.2.3.dmg

Cheers

**Comment by martimpassos** [comment]
Hello, same issue here. Are there plans to fix this?

**Comment by samuello1228** [comment]
I am on MacOS Mojave ver. 10.14.6.
I have created a git repository to share my dmg files.
I have successfully built it from source.
https://github.com/samuello1228/spek-my-build/blob/main/v0.8.4/spek-0.8.4.dmg

**Comment by Joan** [comment]
Getting the _Spek needs to be updated_ error on macOS Monterey 12.5 MBP 16" M1 Pro.
(https://github.com/withmorten/spek-alternative/ works fine though…)

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
