### ISSUE TITLE
[New release] FFmpeg5 & Apple Silicon & HighDPI & ... are available now

### ISSUE THREAD

**Issue by MikeWang000000** [alexkay/spek#231]
This is more of a notice than an issue.

It looks like there hasn't been a new release here in a long time. So I forked spek, fixed some bugs, and made a new release (including Windows x64/arm64 and macOS Intel/Apple Silicon native builds).

The repo is <https://github.com/MikeWang000000/spek-X>.

Hope this helps ：）

**Comment by alexkay** [comment]
Thanks Mike! I'm preparing a new release, any specific commits you want to upstream?

Also a PSA: I'm looking for a maintainer of Windows and macOS builds as I no longer have Windows installed and have no access to Apple hardware.

**Comment by MikeWang000000** [comment]
My code is based on spek-alternative, it's a little different from master now. The update of the ffmpeg related code is important, because `avcodec_decode_audio4()` is no longer available in the latest ffmpeg. I'll make a new PR later.

> Also a PSA: I'm looking for a maintainer of Windows and macOS builds as I no longer have Windows installed and have no access to Apple hardware.

I'm not very familiar with cross-compiling, so I'm using MSYS2 (MinGW) to build Windows binary. I can help compile these binaries if necessary～

**Comment by flopezre** [comment]
Thanks mate 🙌

**Comment by Barough** [comment]
> Thanks Mike! I'm preparing a new release, any specific commits you want to upstream?
> 
> Also a PSA: I'm looking for a maintainer of Windows and macOS builds as I no longer have Windows installed and have no access to Apple hardware.

You could use GitHub Actions build option

**Comment by Barough** [comment]
> Thanks Mike! I'm preparing a new release, any specific commits you want to upstream?

After looking at Mike's Spek-X, so would it be nice to also see the 'Show Filename only & 'Show detailed description' preferences being added here also

**Comment by alexkay** [comment]
It looks like everything here is either addressed or tracked by other issues. Thanks everyone!
