### ISSUE TITLE
Support multiple audio streams

### ISSUE THREAD

**Issue by Erick2317** [alexkay/spek#237]
As an **enhancement** or **new feature**, **files** with **multiple audio streams** in a **MKV**, **MP4** or **M2TS** container, only the **first audio stream** of the **file** is **recognized** while the other **streams** are **ignored** by the program (**issue** #134 also mention this). Here are some examples:
![2022-08-02](https://user-images.githubusercontent.com/91224267/182530613-771f5eb7-8e94-48ad-8516-387d9e9ac64a.png)
![00006 m2ts](https://user-images.githubusercontent.com/91224267/182530662-175d702d-5061-4577-82fe-eb753da3b55f.png)
![2022-08-02 (1)](https://user-images.githubusercontent.com/91224267/182530744-3cc56625-3516-4067-b7d9-75d5d286da3b.png)
![youtube-dl test video ''_ä↭𝕐  BaW_jenozKc mkv](https://user-images.githubusercontent.com/91224267/182530800-7ce1d6c5-b1ea-4397-b22a-1d1c8169e285.png)

**Comment by alexkay** [comment]
v0.8.4 supports this, cycling between audio streams is done with `s`:

* https://github.com/alexkay/spek/tree/v0.8.4#new-features-and-enhancements
* https://github.com/alexkay/spek/releases/tag/v0.8.4

There's no prebuilt package for Windows yet, stay tuned.

**Comment by Erick2317** [comment]
I'll keep an eye on it, thanks!
