### ISSUE TITLE
Failed to compile on void linux

### ISSUE THREAD

**Issue by GuyWithCake** [alexkay/spek#238]
When running ./configure.sh I get the following error:

```
checking for libavformat >= 57.33.100... no
configure: error: Package requirements (libavformat >= 57.33.100) were not met:

No package 'libavformat' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables AVFORMAT_CFLAGS
and AVFORMAT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

The package was clearly installed though, see output when running _sudo xbps-install libavformat_ :

`Package libavformat already installed.`

I would appreciate any help and thanks in advance!

Edit: I run the musl lib version of void linux if it changes anything.

**Comment by absolutelynothinghere** [comment]
A fork of Spek called `spek-alternative` is available in the Void Linux repos, just download that.
