### ISSUE TITLE
When will the windows version be compiled?

### ISSUE THREAD

**Issue by AlphaHasher** [alexkay/spek#241]

**Comment by kieeeee24Self** [comment]
Wait

**Comment by maximousblk** [comment]
are there compile instructions for windows?

**Comment by Barough** [comment]
Would be very nice to get some new Windows compiles available

**Comment by drafter0815** [comment]
Hello,
I am also very keen on the new version.

Best Regards
Markus

**Comment by maximousblk** [comment]
i have no problem building from source but there are no instructions on how to build it, specially for windows

**Comment by alexkay** [comment]
I added updated beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by sylikc** [comment]
> The best solution for the compiles is to use Github Actions and set it up so that it check the sourcecode say once every 2 weeks or so and if there has been any changes/additions to the code so does it make a new build and makes it available.

@Barough if you're able to get this building with GH Actions, I'm all ears.  I couldn't figure it out for the life of me, how to even start cross compiling with GH Actions.

> i have no problem building from source but there are no instructions on how to build it, specially for windows

@maximousblk  So I was just able to build this with MSYS2 on Windows.  Took hours of hacking away at files, but.. it popped out `spek.exe` and it runs... haven't tested all functionality yet though.

It isn't standalone like a single EXE that was in 0.8.2, but I'll take what I can get.

**Comment by sylikc** [comment]
lol @alexkay you just built it right as I was writing the comment, as I was going to do a writeup.  Cool!  Would you be able to do a write-up as to what the requirements and a short blurb as to how to get it built?

**Comment by alexkay** [comment]
@sylikc, I updated instructions, see https://github.com/alexkay/spek/blob/master/dist/win/README.md

This involves cross-compiling on Linux (I use Debian stable) and bundling the MSI on Windows. Let me know if the steps don't work for you.

Integrating that with GH Actions is probably possible, but now that I have a working set up locally I'd rather spend the little time I have on other areas (macOS, HiDPI support, etc).

**Comment by sylikc** [comment]
Thanks @alexkay I'll read through the updated docs and see if I can come up with a GH Action that works if you'd like.  I'm still kinda new to GH Actions, just having it working on [my JPEGView project](https://github.com/sylikc/jpegview/actions)

I'll start testing some of it if you'd be interested in having autobuilds... and I can issue a PR if I get it working?

**Comment by alexkay** [comment]
Sounds like a plan, thank you!
