### ISSUE TITLE
Hello, Spek error MP3 duration

### ISSUE THREAD

**Issue by Dante1880** [alexkay/spek#242]
Hello,

Spek shows a wrong duration in a MP3, for the same MP3 gives error in low bitrate.

Converted with SWITCH from NCH SOFTWARE.

What happens?

Thank you.

https://mega.nz/file/Z0VwwTKa#tPTA-OD5Llp-DabEX5zx4O4QX9lMJupHhL5Xs9h4Kyg

https://mega.nz/folder/whdCEDYL#sdfIjLupMvzKniMkg54bmA

**Comment by alexkay** [comment]
Could you try 0.8.5, I just made a beta version of the Windows build, it should be using much newer ffmpeg libraries: https://github.com/alexkay/spek/releases/tag/v0.8.5

If it still doesn't work, could you share a sample so that I could troubleshoot?
