### ISSUE TITLE
Spek does not open on Mac OS Mojave 10.14.6

### ISSUE THREAD

**Issue by theSundanceKid1980** [alexkay/spek#245]
When I try to launch the application I get a message saying that "Spek quit unexpectedly...". Logs provided below. 

Process:               Spek [24750]
Path:                  /Applications/Spek.app/Contents/MacOS/Spek
Identifier:            org.spek-project
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Spek [24750]
User ID:               501

Date/Time:             2022-10-29 17:10:03.963 -0400
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Anonymous UUID:        BEC3263B-53BF-3745-2211-D255655BFB2E

Sleep/Wake UUID:       F5293BC5-36BD-4640-9BD8-C3E4A0222B6B

Time Awake Since Boot: 210000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [24750]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x948b8b5b  ebx: 0x00001000  ecx: 0x00001000  edx: 0x241499f5
  edi: 0xbffffccc  esi: 0x00000001  ebp: 0xbffffc38  esp: 0xbffffc34
   ss: 0x00000023  efl: 0x00010217  eip: 0x00001720   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 8320253
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro9,1, BootROM 228.0.0.0.0, 4 processors, Intel Core i7, 2.3 GHz, 8 GB, SMC 2.1f175
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT650MItem, NVIDIA GeForce GT 650M, spdisplays_pcie_device, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x859B, 0x435434473353313630424D2E4D3136464B44
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x859B, 0x435434473353313630424D2E4D3136464B44
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1325.2)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: CT500MX500SSD1, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by xxVOXxx** [comment]
I wasn't able to get Spek 0.8.3 working on OSX 10.12 or higher, but this version I found awhile back works great.  Tested up to 10.14 Mojave. [https://www.dropbox.com/s/9dtdz5bn36gijxc/Spek-0.8.4-alpha%20%5BMAC%20OSX%2010.12%2B%5D.dmg?dl=1](url)

**Comment by adapoon** [comment]
I have successfully built it from source.
https://github.com/samuello1228/spek-my-build/blob/main/v0.8.4/spek-0.8.4.dmg
Could you please try my build?

**Comment by samuello1228** [comment]
I have successfully built it from source.
https://github.com/samuello1228/spek-my-build/blob/main/v0.8.4/spek-0.8.4.dmg
Could you please try my build?

**Comment by NicolasReibnitz** [comment]
@samuello1228 version works like a charm! Thanks!

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by samuello1228** [comment]
I got this message "You have macOS 10.14.6. The application requires macOS 10.15 or later."

**Comment by alexkay** [comment]
@samuello1228, unfortunately the earliest version I have access to is 10.15 (Catalina).

**Comment by xxVOXxx** [comment]
That's strange, the info.plist says MinimumSystemVersion 10.5, but I'm also getting the prohibited symbol on the Spek.app...

I have 10.14 Mojave, @alexkay I am willing to compile it on my lower system version if you can walk me through it if that's the issue.

**Comment by samuello1228** [comment]
@xxVOXxx I have successfully compile it. You can try it.
https://github.com/samuello1228/spek-my-build/blob/main/v0.8.5/spek-0.8.5.dmg

**Comment by xxVOXxx** [comment]
> @xxVOXxx I have successfully compile it. You can try it. https://github.com/samuello1228/spek-my-build/blob/main/v0.8.5/spek-0.8.5.dmg

thanks @samuello1228! I tried it, however it gives this error message on run in 10.14.6

![ss](https://user-images.githubusercontent.com/68666900/217106746-00c3c38b-7505-4dda-ae83-992bd9726c0a.png)

**Comment by samuello1228** [comment]
I am running on macOS 10.14.6 (18G9323).
I can run it on my MacBook Pro.
I have no ideas why you cannot open it.

**Comment by xxVOXxx** [comment]
> I am running on macOS 10.14.6 (18G9323). I can run it on my MacBook Pro. I have no ideas why you cannot open it.
> 
> Can you try 0.8.4? https://github.com/samuello1228/spek-my-build/blob/main/v0.8.4/spek-0.8.4.dmg
> 
> I can teach you how to compile it, if you want.

I tried your 0.8.4 also, same error.  I did see in the build notes .txt about installing dependencies.  Maybe this is the issue?  I was hoping not to have to install anything else to run the Spek.app natively on MacOS.  I would definitely be willing to try to compile it and would appreciate the help! I have access to as low as 10.8 Mountain Lion if we want to try to get it working for everyone on a lower OS as well.

**Comment by samuello1228** [comment]
First, you need to install Xcode Developer Tools from Apple
https://docs.brew.sh/Installation#macos-requirements
You can simply run:
xcode-select --install

Then, you need to install homebrew.
https://brew.sh/
You can simply copy the command and run
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by alexkay** [comment]
> That's strange, the info.plist says MinimumSystemVersion 10.5, but I'm also getting the prohibited symbol on the Spek.app...

I need to update it to list 10.15, I think the min is whatever system the package is built on.

> I have 10.14 Mojave, @alexkay I am willing to compile it on my lower system version if you can walk me through it if that's the issue.

Instructions are in ./dist/osx

**Comment by xxVOXxx** [comment]
> First, you need to install "Command Line Tools (CLT) for Xcode" from Apple https://docs.brew.sh/Installation#macos-requirements You can simply run: xcode-select --install
> 
> Then, you need to install homebrew. https://brew.sh/ You can simply copy the command and run /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Ok @samuello1228  check, Command Line Tools and Homebrew installed


@alexkay where do I find ./dist/osx?

**Comment by alexkay** [comment]
> @alexkay where do I find ./dist/osx?

In the repo: https://github.com/alexkay/spek/tree/master/dist/osx

**Comment by samuello1228** [comment]
@xxVOXxx 
I have successfully run different versions of MacOS (from Lion to Catalina) in Virtualbox. I can also reproduce your error message in Mojave. The problem has been fixed by following the [README.md](https://github.com/alexkay/spek/blob/master/dist/osx/README.md) (Fix libbrotli loader_path). Can you try again? Thank you.

**Comment by xxVOXxx** [comment]
@samuello1228 thanks for the reply.  So I _was_ able to finally get Spek 0.8.5 running on my main Mojave machine using your and @alexkay's instructions to install dependencies in homebrew back in February, but since that solution requires the end user to install homebrew I was hoping we would find a way to fix it natively and it sounds like you did.  I installed your 0.8.5 dmg file (updated 3 weeks ago) on a different Mojave machine without homebrew or the dependencies installed and it WORKED! So whatever you did, thank you and so far so good no errors.
