### ISSUE TITLE
Y-axis scale and/or low energy cutoff

### ISSUE THREAD

**Issue by balaccord** [alexkay/spek#248]
Very fast and tiny, thanks)

Sorry. opened before reading help. After it I saw the energy cutoff feature exists already and edited the text but could not edit the header

I didn't find how to scale the Y-axis (kHz)

Let's take the 192 kHz audio as an example. The chart's height is 96 kHz. But these kilohertzes are all here even in case of the total blackness in the upper frequences. So the chart's height is shorter and thus the pixel resolution is worse than they may be in between these energy borders

**Comment by alexkay** [comment]
The new version supports this, use `u` and `U` to change the upper limit:
* http://help.spek.cc/man-0.8.5.html
* https://github.com/alexkay/spek/releases/tag/v0.8.5
