### ISSUE TITLE
No longer function on Fedora

### ISSUE THREAD

**Issue by thwaller** [alexkay/spek#252]
Recently Spek has stopped working on Fedora, it stopped displaying the graphical spectrum. I have also since noticed that it is no longer on Flatpak or DNF. I see that a release was done solely to get it back into the Debian repos, but it does bring the question ... is this software essentially no longer being maintained?

I also attempted to build from tarball, but it error on a ffmpeg supplied package that is in fact installed, and installed to its default location. I am happy to provide complete details for what I attempted and the exact errors received, but I Also have no interest to force an install of outdated software. I would prefer to change and adjust now rather than prolong those steps. I understand that people have life to deal with, but it would also be good to know the status of the project.

**Comment by alexkay** [comment]
> I am happy to provide complete details for what I attempted and the exact errors received

Please do. Include the build log and the ffmpeg version you have installed.

**Comment by alexkay** [comment]
Closing until the build logs are added.
