### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [alexkay/spek#253]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Editors](https://github.com/forart/HyMPS/blob/main/Aeditors.md) - [Tools](https://github.com/forart/HyMPS/edit/main/Aeditors.md#tools-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/alexkay/spek/)
(generator URL: https://flat.badgen.net/github/license/alexkay/spek/)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by powerjungle** [comment]
The LICENSE.md file can be split into LICENSE which contains only the legal terms for GNU GPLv3 and CREDITS.md which contains everything else from the file or something like that.

**Comment by forart** [comment]
Hi there, thanks for the timely reply !

We corrected both badge (now OWN) and link.

We are sorting resources alphabetically (as you can see in [DAWs](https://github.com/forart/HyMPS/blob/main/DAWs.md#audio---daws-) and [Libraries](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#audio---libraries-) pages) but we recently decided to introduce a different - hopefully - more effective approach.
Projects will be grouped+sorted in this "chain": Section > Subsection > Language > License > Name (alphabetical)

Check out the 1st test in the Generic subsection of the Editors page:

https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic-

Do you think this new approach could better foster collaboration between devs ?

Thanks again and, if you like/need, let us know (by replying to [our discussions](https://github.com/forart/HyMPS/discussions)) how we can support listed projects.

Last but not least, Happy New Year !

**Comment by powerjungle** [comment]
> Hi there, thanks for the timely reply !

No problem, but I'm not actively part of the development.

> We've changed both badge (now shows "OWN") and link at the moment.

Well, it's kinda misleading, because this project doesn't actually have it's "own" license. Although I don't have any ideas for a better name.

> Do you think this new approach could better foster collaboration between devs ?

Me personally, I'm not sure. It's a good idea, but devs probably won't be thinking too much about it.

**Comment by alexkay** [comment]
The licence file clearly states it's GPLv3: https://github.com/alexkay/spek/blob/f209ec7c89c231754f5dedaf6d633de1a6fa996b/LICENCE.md?plain=1#L1-L4

However I can see GitHub is not detecting it correctly. #257 should fix this.
