### ISSUE TITLE
Silicon M1 support

### ISSUE THREAD

**Issue by DJResQ** [alexkay/spek#254]
Hi, thanks a lot for Spek
I use it for a long time now

is there any official release for Silicon please?
I browsed the forum and i see 2 different alternatives.

Can anybody recommend which one is best to use please?

**Comment by ethiapath** [comment]
Also interested in this issue

**Comment by DJResQ** [comment]
@ethiapath I am using this one, so far so good 

https://github.com/withmorten/spek-alternative

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
