### ISSUE TITLE
Binary packages for Windows and macOS

### ISSUE THREAD

**Issue by Barough** [alexkay/spek#255]
@alexkay - Why dont you use GitHub Actions build functions to build/compile all Binary packages that spek supports?

**Comment by samuello1228** [comment]
@Barough Can you teach me how to do this? I have successfully built the binary packages (dmg file) on macOS Mojave.
You can find my dmg file in the link:
https://github.com/samuello1228/spek-my-build/blob/main/v0.8.5/spek-0.8.5.dmg

**Comment by Barough** [comment]
@samuello1228 Dont know how to setup GitHub Actions. GHA seems to be used a lot out there to compile packages for different OS's. That's why i suggested it.

**Comment by alexkay** [comment]
I added updated beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

A macOS build is next in line.

**Comment by Barough** [comment]
Been testing the Windows Beta with a bunch of different files and it works as it should

Noticed in the 'About' that the copyright years in not correct. I currently say 2013-2013.

**Comment by alexkay** [comment]
Thank you @Barough! I'll fix the copyright message in a future release.
