### ISSUE TITLE
Build failure on arm64 and mips64el

### ISSUE THREAD

**Issue by matteobin** [alexkay/spek#262]
The issue reported by @MikeWang000000 in #232 is causing a build failure
on Debian arm64 and mips64el repository:
https://buildd.debian.org/status/fetch.php?pkg=spek&arch=arm64&ver=0.8.5%2Bdfsg-1&stamp=1674401278&raw=0
https://buildd.debian.org/status/fetch.php?pkg=spek&arch=mips64el&ver=0.8.5%2Bdfsg-1&stamp=1674401012&raw=0

I'm going to use Mike's patch to momentarily fix this issue.

`--- a/tests/test-fft.cc`
`+++ b/tests/test-fft.cc`
`@@ -62,7 +62,7 @@ static void test_sine()`
`                 if (i == k) {`
`                     continue;`
`                 }`
`-                if (plan->get_output(i) > -150.0f) {`
`+                if (plan->get_output(i) > -149.0f) {`
`                     silence = false;`
`                     break;`
`                 }`

**Comment by alexkay** [comment]
Merged, thank you guys!
