### ISSUE TITLE
"Spek Warning – Cannot set locale to language…"

### ISSUE THREAD

**Issue by thomaskyhn** [alexkay/spek#269]
When launching Spek, I get this error message:

"Spek Warning
Cannot set locale to language "English (Denmark)"."

<img width="270" alt="Screenshot 2023-02-06 at 20 55 48" src="https://user-images.githubusercontent.com/22273777/217210192-34726053-6f9f-4f4e-a5cf-a1c94fd041bb.png">

After clicking on OK, everything appears to work as it should.

(MacBook Pro M1 Max, macOS 13.2.)

. . .

Language and Region settings:

User Settings:

  Requested Linguistic Assets:	en, da, nb, nn, de, pt, fr, it, sv, nl, fi, es, hu, pl, vi, tr
  Siri Language:	en-GB
  Siri Voice Gender:	Male
  Siri Voice Language:	en-GB
  Calendar:	Gregorian
  Country Code:	DK
  Current Input Source:	com.apple.keylayout.Danish
  Language Code:	en
  Locale:	en_DK
  Preferred Interface Languages:	en-US, da-DK
  Uses Metric System:	Yes

System Settings:

  Country Code:	DK
  OS Interface Languages:	en, en-GB, en-AU, en-IN, zh-Hans, zh-Hant, zh-HK, ja, es, es-419, fr, fr-CA, de, ru, pt-BR, pt-PT, it, ko, tr, nl, ar, th, sv, da, vi, nb, pl, fi, id, he, el, ro, hu, cs, ca, sk, uk, hr, ms, hi
  System Preferred Interface Languages:	en-US, da-DK
  Locale:	en_DK
  Text Direction:	Left-To-Right
  Uses Metric System:	No

Recovery Partition Settings:

  Keyboard Code:	9
  Locale:	en

**Comment by alexkay** [comment]
@thomaskyhn and @PrimulaX, could you try updated .dmg file from https://github.com/alexkay/spek/releases/tag/v0.8.5? Let me know if you are still seeing the warning.

**Comment by PrimulaX** [comment]
@alexkay no warning, its good.

**Comment by PrimulaX** [comment]
`.dmg` file is quite big tho, unlike the alternative version I had before

**Comment by alexkay** [comment]
> `.dmg` file is quite big tho, unlike the alternative version I had before

It's likely because the ffmpeg build needs to be customised to turn off unnecessary features. I'll look into it for a future version.

**Comment by thomaskyhn** [comment]
> @thomaskyhn and @PrimulaX, could you try the updated .dmg file from https://github.com/alexkay/spek/releases/tag/v0.8.5? Let me know if you are still seeing the warning.

I don't see the warning with this version.
