### ISSUE TITLE
Spek cannot handle aiff files with ID3v2 chunk

### ISSUE THREAD

**Issue by tworkool** [alexkay/spek#282]
Hello,
I have been experimenting with ffmpeg recently. I am using Spek to analyze in and outputs. In my current case I am converting flac files to aiff files.
In ffmpeg I am adding ID3v2 tags. When analyzing the input flac Spek is analyzing everything correctly. The output aiff however shows that the file has no audio channels.
Here is the ffmpeg command (might help or is faulty?):
**ffmpeg -i test.flac -i cover.png -map_metadata 0 -acodec pcm_s16be -ar 44100 -id3v2_version 4 -write_id3v2 1 -f aiff out.aiff**
To explain:
* _-i test.flac_: input audio flac on stream 0
* _-i cover.png_: input cover image on stream 1
* _-map_metadata 0_ map metadata of stream 0
* _-acodec pcm_s16be_: audio codec PCM signed 16bit Big Endian
* _-ar 44100_: audio sampling rate 44.1 kHz
* _-id3v2_version 4 -write_id3v2 1_ select ID3v2 version 4 and write ID3v2 chunk to output stream 1 (append to audio file i guess). Here, when setting it to stream 0 (audio stream) it probably adds it on top. But in this case Spek can analyze the track (the software I am using - Rekordbox - can only analyze the track when the ID3v2 chunk is on stream 1)
* _-f aiff_ output file format aiff
* _out.aiff_ output file name

The input analysis of the flac in Spek looks like this:
![test flac](https://user-images.githubusercontent.com/55762879/232625162-4b6832ca-aee8-42be-a4c4-c263a0de0051.png)

The output analysis of the aiff in Spek looks like this:
![out3 aiff](https://user-images.githubusercontent.com/55762879/232625236-f7085e36-f5fc-4753-be20-55fb45160564.png)

**Comment by alexkay** [comment]
Could you try it with v0.8.5?

https://www.spek.cc/p/download

**Comment by tworkool** [comment]
@alexkay yes, sry. As I posted it I realized I should probably try with the newest version...

**Comment by tworkool** [comment]
Ok, it works! sry for the inconvenience. good piece of software ;)
