### ISSUE TITLE
link to legacy build

### ISSUE THREAD

**Issue by xaosm-os** [alexkay/spek#304]
im on a mac os x 10.14 Mojave 
i don't update since, because my audio interface won't be usable anymore. 
can you link legacy SPEK build that would still work with older OS's?
thanks.

**Comment by alexkay** [comment]
Builds for the old Spek versions are available on the Releases page: https://github.com/alexkay/spek/releases

**Comment by xaosm-os** [comment]
thanks! didnt find it before. cheers
