### ISSUE TITLE
Window content cropped on high DPI scaling

### ISSUE THREAD

**Issue by IdolR** [alexkay/spek#33]
I run my laptop graphic card on Windows 7 @1920x1080 with large DPI scaling enabled (200%) as a result the topmost and leftmost sides of Spek's window contents are clipped away.
See here http://oi46.tinypic.com/34h7uir.jpg

**Comment by hanbang-wang** [comment]
Same here.

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
