### ISSUE TITLE
doesnt work on OSX 10.8.5

### ISSUE THREAD

**Issue by designerfuzzi** [alexkay/spek#57]
after starting spek, the dialog window shows up and direct after the app crashes with

"Crashed Thread:  Unknown

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0xac988238  ebx: 0x0052729e  ecx: 0x967fc87b  edx: 0x03e2aa64
  edi: 0x9665927e  esi: 0x00000000  ebp: 0xbfffe4c8  esp: 0xbfffe470
   ss: 0x00000023  efl: 0x00000246  eip: 0x966592a0   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x03ed4000
Logical CPU: 1

Binary images description not available"

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by designerfuzzi** [comment]
sadly i can not test unless i compile the stuff in OSX 10.14 as this is after all a 10 year old issue. Nether the less your support was and is appreciated. Thanks.
