### ISSUE TITLE
crashes on open in Yosemite

### ISSUE THREAD

**Issue by brianlg** [alexkay/spek#77]
Spek 0.8.3 crashes on open in Yosemite.
I uninstalled/installed fresh and problem persists.

Spek quit unexpectedly

**Comment by GitTheHellOutaHere** [comment]
Well that’s strange!

I started to write a comment saying ditto for Spek 0.8.3 on 10.10.5.
It had crashed twice in a row right after installation.

I opened it once more and now it’s working.

**Comment by albertcarrete** [comment]
Same issue here as well. Running Spek 0.8.2 on 10.10.15. 

Crashes upon open a handful of times and then eventually just works.

**Comment by netinept** [comment]
crashes for me every time on OS 10.11.2

**Comment by JackSzwergold** [comment]
Add me to the list of folks who can’t get Spek to launch on macOS Sierra (10.12.2). Crashes immediately when opened or when a file is dragged onto it. The interesting thing is I downloaded the DMG from the official Spek website and while the DMG is named `spek-0.8.3.dmg` Checking the actual version of the application using “Get Info” shows the version to be 0.8.2. Weird.

**Comment by alexkay** [comment]
@JackSzwergold, Sierra crash is issue #107. See comments, there's a pre-release build that should work.

**Comment by alexkay** [comment]
Also, closing this one -- I can't support older macOS versions.
