### ISSUE TITLE
can you explain this comment ?

### ISSUE THREAD

**Issue by user597** [alexkay/spek#79]
hi 
can you explain this TODO  in spek-window.cc ?

```c
// TODO: s/audio/media/
static const char *audio_extensions[] = {
    "3gp",
    "aac",
    "aif",
    "aifc",
    "aiff",
    "amr",
    "awb",
...
```

**Comment by Corak667** [comment]
I think he wants to add support for all audio extentions and formats (ffmpeg.org/general.html#Audio-Codecs) that already supported decoding by FFMPEG code.

**Comment by alexkay** [comment]
@user597: Spek can already open video files, this comment is about extending the list of extensions with all video files it can open. Right now Spek analyzes the first audio stream it finds in a video file, selecting audio streams is #18.
