### ISSUE TITLE
Errors while compiling spek-fft.cc in Ubuntu 14.10

### ISSUE THREAD

**Issue by vrd** [alexkay/spek#81]
Tried to install spek in Ubuntu 14.10. Had some errors:

spek-fft.cc: In function ‘spek_fft_plan* spek_fft_plan_new(int)’:
spek-fft.cc:31:82: error: ‘malloc’ was not declared in this scope
     struct spek_fft_plan *p = (spek_fft_plan*)malloc(sizeof(struct spek_fft_plan));
                                                                                  ^
spek-fft.cc: In function ‘void spek_fft_delete(spek_fft_plan*)’:
spek-fft.cc:67:11: error: ‘free’ was not declared in this scope
     free(p);
           ^

After googling this issue, I added string #include <cstdlib> in spek-fft.cc and compiled successfully.

**Comment by denysvitali** [comment]
+1, Awesome, you saved me :P

**Comment by 550** [comment]
Thanks for your response vrd, that did the trick, adding

#include <stdlib.h>

at the top of spek-fft.cc fixed the issue for me.

**Comment by alexkay** [comment]
This is fixed in master.
