### ISSUE TITLE
Opus has different scale compared to Vorbis and FLAC

### ISSUE THREAD

**Issue by nixxquality** [alexkay/spek#83]
Why does the scale on Opus go up to 24 kHz compared to Vorbis and FLAC that go up to 22 kHz?

http://imgur.com/a/eEJjL

**Comment by skimmilk** [comment]
The audio sample rate of number three is 48khz, while the sample rate of the first two are 44.1khz.  

Audio frequencies go up to the sample rate divided by two, so the highest frequency possible of an audio sample sampled at 44.1khz is around 22khz, with 48khz at 24khz.  Spec only shows the full spectrum of all possible frequencies.

**Comment by nixxquality** [comment]
So it's my fault for encoding the Opus file with different settings?
