### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [alexkay/spek#88]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [0.8.2 release files](https://code.google.com/p/spek/downloads/list) to somewhere else? (eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by alexkay** [comment]
Done. I'll update the website and the README later this week.

Thank you for flagging!

**Comment by tsparber** [comment]
Thank you! (Refs https://github.com/caskroom/homebrew-cask/pull/17330)
